pipeline {
  agent {
      docker {
        image 'python:3.9-slim'
      }
  }

  stages {
      stage('build'){
        when {
          changeset "**/vote/**"
        }
        steps {
          echo 'Compiling vote app'
          dir('vote'){
            sh 'pip install -r requirements.txt'
          }
        }
      }

      stage('test'){
        when {
          changeset "**/vote/**"
        }
        steps {
          echo 'Running Unit Test on vote app'
          dir('vote'){
            sh 'nosetest -v'
          }
        }
      }
  }

  post {
    always {
      echo 'Pipeline for vote is complete..'
    }
    failure {
      slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
    success {  
      slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
    }
  }

}